version: '3'
services:
  ### Posgres database for Products
  db-products:
    container_name: cqrs-db-products
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_products
      POSTGRES_USER: imagina
      POSTGRES_PASSWORD: Test123
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  ### Zookeeper
  zookeeper:
    container_name: cqrs-zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ### Kafka
  kafka:
    container_name: cqrs-kafka
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      
  ### Redis
  redis:
    container_name: cqrs-redis
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - 6379
    restart: unless-stopped